#DROPBOX:=/home/semir/Dropbox/MicroBitDesign/MCU/
#STM32CUBEPROG:= $(DROPBOX)/st-microelectronics/stmcubeprog/bin/STM32_Programmer.sh -vb 1 -q -c port=SWD 
#GNUGCC = $(DROPBOX)/gcc/gcc-arm-none-eabi-10-2020-q4-major/bin
#CC = $(GNUGCC)/arm-none-eabi-gcc
#OBJCOPY = $(GNUGCC)/arm-none-eabi-objcopy
#SIZE =  $(GNUGCC)/arm-none-eabi-size
#OBJDUMP = $(GNUGCC)/arm-none-eabi-objdump


STM32CUBEPROG:= /home/mahir/stmcubeprog/bin/STM32_Programmer.sh -vb 1 -q -c port=SWD

CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
SIZE =  arm-none-eabi-size
OBJDUMP = arm-none-eabi-objdump

